### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by kgembedding2019** [alberto-valdeolivas/RWR-MH#2]
Error in contrib.url(repos, "source") :
  trying to use CRAN without setting a mirror
Calls: install.packages.if.necessary -> install.packages -> contrib.url
: Warning messages:
1: In library(package, lib.loc = lib.loc, character.only = TRUE, logical.return = TRUE,  :
  there is no package called 'biomaRt'
2: In library(package, lib.loc = lib.loc, character.only = TRUE, logical.return = TRUE,  :
  there is no package called 'supraHex'
3: package 'hexbin' was built under R version 3.5.3
4: In library(package, lib.loc = lib.loc, character.only = TRUE, logical.return = TRUE,  :
  there is no package called 'igraph'

**Comment by alberto-valdeolivas** [comment]
Hello! I am very sorry, I totally skipped your message. I use to get emails with the issues, but I maybe also did not see the email. Thanks for your email, it seems that in some cases we need to specify a CRAN mirror to install the packages. 

Best regards,
Alberto.
