### ISSUE TITLE
Run RWR-M without the Pathway Network

### ISSUE THREAD

**Issue by fratajcz** [alberto-valdeolivas/RWR-MH#3]
Hi!

Great job at making RWR-M and -MH accessible, even 4 years after publication I can still run it with only minor installation issues. 

One question, I want to benchmark RWR-M against a few other methods that do not make use of Pathway information. In fact, I will use Pathway Enrichment Analysis in the external validation pipeline of my results, so this would give RWR-M an unfair headstart.

How can I run RWR-M without the Pathway information?

I have tried the following parameter file:

```
1. Global Restart Probability (r):	0.7
2. Inter-Layer Jump Probability (delta):	0
3. Layers Restart Probability - (PPI, PATH, COEX) (tau): 	1.5,0,1.5
4. Number of Top Genes to be included in the output network (K):	20
```

The layers restart probability makes sure that we don't start at the pathway layer and the inter-layer jump probability makes sure we don't visit it during the walks. Sadly this also prohibits walking from PPI to COEX.

BTW setting a probability to 1.5 hurts me, but they have to sum up to 3.

But I get the following error:

```
[1] "Reading arguments..."
[1] "Global restart probability: 0.7"
[1] "Inter-Layer Jump Probability: 0"
[1] "Layers Restart Probability:  1.5,0,1.5"
[1] "Number of Top results to be displayed in the output network: 20"
[1] "Reading Multiplex Layers..."
[1] "Getting the Column Normalization..."
Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'x' in selecting a method for function 't': Cholmod error 'problem too large' at file ../Core/cholmod_dense.c, line 102
Calls: t ... / -> / -> as -> asMethod -> .handleSimpleError -> h
Execution halted
```

can you help me out?

**Comment by alberto-valdeolivas** [comment]
Hello @fratajcz ,

Thanks for your interest. I would suggest to use our related R package: 

https://github.com/alberto-valdeolivas/RandomWalkRestartMH
https://alberto-valdeolivas.github.io/RandomWalkRestartMH/

There you can easily select which networks to use. 

Please let me know if this helps. 

Alberto
