### ISSUE TITLE
No DISGENET_DATA file in the code

### ISSUE THREAD

**Issue by Chengyuanyue** [alberto-valdeolivas/RWR-MH#4]
Hi!

I am very interested in your excellent job. But when I tried to repeat the results in the paper, I had a problem in LOOCV step, then I found there is no DISGENET_DATA file in the code. Could you please send me DISGENET_DATA file(my email is a13730374634@163.com) or upload it.
Thank you very much!

![image](https://github.com/alberto-valdeolivas/RWR-MH/assets/131670096/be40482f-bacc-47e6-a79b-63d896541ad0)

**Comment by alberto-valdeolivas** [comment]
Hello! 

Thanks for your interest in our work and repo. 

Those files are generated in this [script](https://github.com/alberto-valdeolivas/RWR-MH/blob/master/Scripts_and_Files/LOOCV/Disgenet_Generation_Input_LOOCV.R). You have to run it before running the script you are talking about.  

Best regards,
Alberto.

**Comment by Chengyuanyue** [comment]
Thank you so much!
